version: 0.0
os: linux
files:
  - source: /NotificationServer.jar
    destination: /build/libs/
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
